name: Corey Senger
title: Corey Senger
markdown: kramdown
collections_dir: collections
collections:
  papers:
    output: true
    permalink: /posts/:year/:month/:day/:title
    layout: paper
  socials:
    social: true
sass:
  style: compressed
livereload: true